### ISSUE TITLE
peewee.OperationalError: no such table: users

### ISSUE THREAD

**Issue by acuere** [netbriler/aiogram-sqlalchemy-template#2]
How to solve this problem . On windows 10, when start the bot it raises error. 
Please explain more. I am new .

**Comment by netbriler** [comment]
You have to migrate the database first and then run the bot.

https://github.com/netbriler/aiogram-peewee-template#upgrade-database

**Comment by acuere** [comment]
> You have to migrate the database first and then run the bot.
> 
> https://github.com/netbriler/aiogram-peewee-template#upgrade-database

Thanks much.
